### ISSUE TITLE
Add favicon of DCP logo

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/itd-project-list#2]
![image](https://user-images.githubusercontent.com/13967925/56537345-4a3e2b00-652e-11e9-8108-48c8620f44ec.png)

**Comment by trbmcginnis** [comment]
https://github.com/NYCPlanning/labs-applicantmaps/pull/363/files

https://github.com/NYCPlanning/labs-zap-search/pull/455/files#diff-edb274d8c594429b8ccc684d79d771f6

https://www.w3.org/2005/10/howto-favicon

**Comment by trbmcginnis** [comment]
`<link rel="icon" type="image/png" sizes="32x32" href="public/your-image.png">`
